<?php

/**
 * @file
 * Provides integration with Tagify and Dragsort libraries.
 */

/**
 * Implements hook_library_info_alter().
 */
function tagify_library_info_alter(&$libraries, $module) {
  if ($module == 'tagify') {
    // In case that the libraries are included locally, use those instead of the
    // CDN.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');
    $current_libraries = [
      'tagify' => [
        'js' => 'tagify/dist/tagify.min.js',
        'css' => 'tagify/dist/tagify.css',
      ],
      'tagify_polyfils' => [
        'js' => 'tagify/dist/tagify.polyfills.min.js',
      ],
      'tagify_jquery' => [
        'js' => 'tagify/dist/jQuery.tagify.min.js',
      ],
      'dragsort' => [
        'js' => 'dragsort/dist/dragsort.js',
        'css' => 'dragsort/dist/dragsort.css',
      ],
    ];
    foreach ($current_libraries as $current_library_id => $current_library_type) {
      if (isset($libraries[$current_library_id])) {
        foreach ($current_library_type as $library_type_id => $current_library_file) {
          $path = $library_file_finder->find($current_library_file);
          if ($path) {
            if ($library_type_id === 'css') {
              $libraries[$current_library_id][$library_type_id]['component'] = [
                '/' . $path => [],
              ];
            }
            else {
              $libraries[$current_library_id][$library_type_id] = [
                '/' . $path => ['minified' => TRUE],
              ];
            }
          }
        }
      }
    }
  }
}
